const SEED_JACK = [
  { id: "j1", name: "Booty Builder", area: "Legs", muscle: "Glutes", pbs: [{ reps: 10, kg: 60 }] },
  { id: "j2", name: "Bulgarian Split Squat", area: "Legs", muscle: "Quads", pbs: [{ reps: 10, kg: 6 }] },
  { id: "j3", name: "Calf Press", area: "Legs", muscle: "Calves", pbs: [{ reps: 12, kg: 45 }, { reps: 11, kg: 39 }, { reps: 10, kg: 45 }] },
  { id: "j4", name: "Hack Squat", area: "Legs", muscle: "Quads", pbs: [{ reps: 10, kg: 62 }, { reps: 8, kg: 67 }] },
  { id: "j5", name: "Hip Abduction", area: "Legs", muscle: "Glutes", pbs: [{ reps: 10, kg: 25 }] },
  { id: "j6", name: "Hip Adduction", area: "Legs", muscle: "Glutes", pbs: [{ reps: 12, kg: 28 }] },
  { id: "j7", name: "Leg Extension", area: "Legs", muscle: "Quads", pbs: [{ reps: 12, kg: 47 }, { reps: 11, kg: 47 }, { reps: 10, kg: 54 }] },
  { id: "j8", name: "Leg Press", area: "Legs", muscle: "Quads", pbs: [{ reps: 10, kg: 50 }] },
  { id: "j9", name: "Prone Leg Curl", area: "Legs", muscle: "Hamstrings", pbs: [{ reps: 12, kg: 27 }, { reps: 10, kg: 43 }, { reps: 9, kg: 41 }] },
  { id: "j10", name: "Split Squat", area: "Legs", muscle: "Quads", pbs: [{ reps: 10, kg: 10 }] },
  { id: "j11", name: "Chest Fly", area: "Chest", muscle: "Chest", pbs: [{ reps: 12, kg: 59 }, { reps: 11, kg: 66 }, { reps: 10, kg: 66 }, { reps: 8, kg: 73 }] },
  { id: "j12", name: "Chest Press", area: "Chest", muscle: "Chest", pbs: [{ reps: 12, kg: 27 }, { reps: 10, kg: 45 }] },
  { id: "j13", name: "Converging Chest Press", area: "Chest", muscle: "Chest", pbs: [{ reps: 11, kg: 41 }, { reps: 10, kg: 45 }, { reps: 9, kg: 45 }, { reps: 8, kg: 41 }] },
  { id: "j14", name: "Dumbbell Chest Press", area: "Chest", muscle: "Chest", pbs: [{ reps: 12, kg: 14 }, { reps: 10, kg: 16 }], perHand: true },
  { id: "j15", name: "Diverging Seated Row", area: "Back", muscle: "Upper Back", pbs: [{ reps: 12, kg: 27 }, { reps: 11, kg: 36 }, { reps: 10, kg: 41 }, { reps: 8, kg: 38 }] },
  { id: "j16", name: "Lat Pulldown", area: "Back", muscle: "Lats", pbs: [{ reps: 12, kg: 45 }, { reps: 10, kg: 47 }, { reps: 9, kg: 52 }] },
  { id: "j17", name: "T-Bar Row", area: "Back", muscle: "Upper Back", pbs: [{ reps: 10, kg: 20 }] },
  { id: "j18", name: "Arm Curl", area: "Arms", muscle: "Biceps", pbs: [{ reps: 11, kg: 36 }, { reps: 10, kg: 38 }, { reps: 9, kg: 36 }, { reps: 8, kg: 36 }, { reps: 6, kg: 36 }] },
  { id: "j19", name: "Cable Bicep", area: "Arms", muscle: "Biceps", pbs: [{ reps: 10, kg: 17.1 }, { reps: 9, kg: 17 }, { reps: 8, kg: 17 }] },
  { id: "j20", name: "Cable Tricep Pushdown", area: "Arms", muscle: "Triceps", pbs: [{ reps: 11, kg: 14.7 }, { reps: 10, kg: 27 }, { reps: 9, kg: 19.3 }, { reps: 8, kg: 17 }], positions: ["left", "middle", "right", "upstairs"] },
  { id: "j21", name: "Dumbbell Bicep Curl", area: "Arms", muscle: "Biceps", pbs: [{ reps: 10, kg: 9 }], perHand: true },
  { id: "j22", name: "EZ Bar Curl", area: "Arms", muscle: "Biceps", pbs: [{ reps: 8, kg: 10 }] },
  { id: "j23", name: "Seated Dip", area: "Arms", muscle: "Triceps", pbs: [{ reps: 10, kg: 52 }, { reps: 9, kg: 47 }] },
  { id: "j24", name: "Seated Long Head Bicep", area: "Arms", muscle: "Biceps", pbs: [{ reps: 10, kg: 8 }, { reps: 8, kg: 9 }] },
  { id: "j25", name: "Tricep Extension", area: "Arms", muscle: "Triceps", pbs: [{ reps: 10, kg: 45 }] },
  { id: "j26", name: "Cable Shoulder Raise", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 10, kg: 3.4 }, { reps: 8, kg: 5 }] },
  { id: "j27", name: "Delt Fly", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 11, kg: 39 }, { reps: 10, kg: 52 }, { reps: 9, kg: 52 }, { reps: 8, kg: 52 }] },
  { id: "j28", name: "Rear Delt Fly", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 10, kg: 39 }, { reps: 8, kg: 39 }] },
  { id: "j29", name: "Seated Shoulder Press", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 10, kg: 10 }] },
  { id: "j30", name: "Shoulder Press", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 10, kg: 15 }, { reps: 9, kg: 15 }, { reps: 8, kg: 15 }], perHand: true },
  { id: "j31", name: "Shoulder Swing", area: "Shoulders", muscle: "Delts", pbs: [{ reps: 10, kg: 8 }, { reps: 9, kg: 7 }, { reps: 8, kg: 8 }], perHand: true },
  { id: "j32", name: "Ab Crunch Machine", area: "Abs", muscle: "Abs", pbs: [{ reps: 12, kg: 45 }, { reps: 10, kg: 45 }] },
  { id: "j33", name: "Russian Twists", area: "Abs", muscle: "Abs", pbs: [{ reps: 15, kg: 6 }] },
];